export enum ProfessionalSituationType {
  EMPLOYE = 'EMPLOYE',
  EN_RECHERCHE_EMPLOI = 'EN_RECHERCHE_EMPLOI',
  ENTREPRENEUR = 'ENTREPRENEUR',
  POURSUITE_ETUDES = 'POURSUITE_ETUDES',
  AUTRE = 'AUTRE',
}
